project:
  appname: spring-shiro-dev

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ssmall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: xyb
    druid:
      initial-size: 5 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 20 #最大连接数
  jpa:
    show-sql: true
    database: MYSQL
    hibernate.ddl-auto: update
    properties.hibernate:
      jdbc.batch_size: 10
      order_inserts: true
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      enable_lazy_load_no_trans: true
    open-in-view: true

